version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/requirements"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix"
      prefix-development: "build"
      include: "scope"
    open-pull-requests-limit: 20
    rebase-strategy: auto

  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix"
      prefix-development: "build"
      include: "scope"
    open-pull-requests-limit: 20
    rebase-strategy: auto