FROM python:3.11.5
LABEL maintainer="chichi13"

# Keeping the image up to date and installing node 15
RUN apt-get update -y && apt-get upgrade -y && \
    rm -rf /var/lib/apt/lists/*

# Copy only requirements/ for caching purpose
WORKDIR /app/fast-api

COPY requirements/ requirements/

RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements/dev.txt

COPY app/ /app

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--reload"]